// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        create_patient
        delete_patient
        create_ticket
        update_validation
        add_model
        update_model
        authorize
        is_authorized
        is_admin
        getPatientInfo
        getTicket
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
